[package]
name = "metro-rust-trasfromer-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }
swc = "0.232.111"
swc_common = { version = "0.29.15", features = ["tty-emitter", "sourcemap"] }
swc_ecma_transforms_base = "0.111.56"
swc_ecma_visit = "0.80.20"
string_cache = "0.8.4"
js-sys = "0.3.60"
serde = "1.0.147"
serde-wasm-bindgen = "0.4.5"
swc_ecma_utils = "0.105.37"
serde_json = "1.0.89"


napi = "2.10.15"
napi-derive = "2.10.1"
es_resolve = "0.4.2"
threadpool = "1.8.1"

[build-dependencies]
napi-build = "2.0.1"
